### ISSUE TITLE
按配置文件运行，找不到class

### ISSUE THREAD

**Issue by JackFan90** [ushelp/EasyBackup#2]
找不到cn.easyproject.easybackup.mysql.MySQLTargetFile，是配置有问题吗？

**Comment by ushelp** [comment]
@JackFan90 

我们重新对 application 场景的库进行了打包，请升级到最新版本 3.3.2.

- 如果您使用的是 **EasyBackup Application**，请升级您的库为
 `libs/easybackup_application/easybackup-application.jar`


- 如果您使用的是 **EasyBackup Engine Framework**，请升级您的库为
`libs/easybackup_engine_framework/easybackup-3.3.2-RELEASE.jar`
 或
  ```XML
  <!-- EasyBackup Engine Framework Maven dependency -->
  <dependency>
    <groupId>cn.easyproject</groupId>
    <artifactId>easybackup</artifactId>
    <version>3.3.2-RELEASE</version>
  </dependency>
  ```

**Comment by ushelp** [comment]
Dear Jack,

我们重新对 application 场景的库进行了打包，请升级到最新版本 3.3.2.

   -

   如果您使用的是 *EasyBackup Application*，请升级您的库为
   libs/easybackup_application/easybackup-application.jar
   -

   如果您使用的是 *EasyBackup Engine Framework*，请升级您的库为
   libs/easybackup_engine_framework/easybackup-3.3.2-RELEASE.jar
   或

   
   <dependency>
     <groupId>cn.easyproject</groupId>
     <artifactId>easybackup</artifactId>
     <version>3.3.2-RELEASE</version>
   </dependency>



Thanks and best regards,
Ray

JackFan90 <notifications@github.com> 于2021年1月17日周日 上午12:26写道：

**Comment by JackFan90** [comment]
very nice!
